#!/usr/bin/env python3
"""
AI Review Script
Uses OpenAI API to review PR diffs and detect issues.
"""

import os
import sys
import json
from typing import Dict, Any, List
from openai import OpenAI
from scripts.utils.github_api import GitHubAPI
from scripts.ai_prompt import get_review_prompt


def review_pr_with_ai(diff: str, api_key: str, model: str = "gpt-4o") -> Dict[str, Any]:
    """
    Send PR diff to OpenAI for review using PR-Guardian prompt.
    
    Args:
        diff: PR diff content
        api_key: OpenAI API key
        model: Model to use (default: gpt-4o)
    
    Returns:
        Review result as dictionary
    """
    client = OpenAI(api_key=api_key)
    
    # Use the PR-Guardian prompt from ai_prompt.py
    prompt = get_review_prompt(diff)
    
    try:
        response = client.chat.completions.create(
            model=model,
            messages=[
                {"role": "system", "content": "You are a strict code review agent. Always respond with valid JSON."},
                {"role": "user", "content": prompt}
            ],
            temperature=0.3,
            max_tokens=4000
        )
        
        content = response.choices[0].message.content.strip()
        
        # Try to extract JSON from response
        if content.startswith("```json"):
            content = content[7:]
        if content.startswith("```"):
            content = content[3:]
        if content.endswith("```"):
            content = content[:-3]
        content = content.strip()
        
        result = json.loads(content)
        return result
        
    except json.JSONDecodeError as e:
        print(f"⚠️  Failed to parse AI response as JSON: {e}")
        print(f"Response: {content[:500]}")
        # Return a safe default
        return {
            "decision": "PASS",
            "severity": "LOW",
            "issues": [],
            "suggestions": ["Could not parse AI response. Manual review recommended."],
            "summary": "AI review encountered parsing error"
        }
    except Exception as e:
        print(f"❌ Error calling OpenAI API: {e}")
        raise


def format_review_comment(review_result: Dict[str, Any], pr_number: int) -> str:
    """
    Format AI review results as a GitHub comment.
    """
    decision = review_result.get("decision", "UNKNOWN")
    severity = review_result.get("severity", "NONE")
    issues = review_result.get("issues", [])
    suggestions = review_result.get("suggestions", [])
    summary = review_result.get("summary", "No summary provided")
    
    # Determine emoji based on decision
    emoji = "✅" if decision == "PASS" else "❌"
    
    comment = f"""{emoji} **AI Code Review Results**

**Decision:** {decision}
**Severity:** {severity}
**Summary:** {summary}

"""
    
    if issues:
        comment += "## 🔍 Issues Found\n\n"
        
        # Group issues by severity
        high_issues = [i for i in issues if i.get("severity") == "HIGH"]
        medium_issues = [i for i in issues if i.get("severity") == "MEDIUM"]
        low_issues = [i for i in issues if i.get("severity") == "LOW"]
        
        if high_issues:
            comment += "### 🔴 High Severity\n\n"
            for issue in high_issues:
                file_path = issue.get("file", "unknown")
                line = issue.get("line", "?")
                desc = issue.get("description", "No description")
                code = issue.get("code_snippet", "")
                comment += f"- **{file_path}:{line}** - {desc}\n"
                if code:
                    comment += f"  ```\n  {code}\n  ```\n"
            comment += "\n"
        
        if medium_issues:
            comment += "### 🟡 Medium Severity\n\n"
            for issue in medium_issues[:5]:  # Limit to 5
                file_path = issue.get("file", "unknown")
                line = issue.get("line", "?")
                desc = issue.get("description", "No description")
                comment += f"- **{file_path}:{line}** - {desc}\n"
            comment += "\n"
        
        if low_issues:
            comment += "### 🟢 Low Severity\n\n"
            for issue in low_issues[:3]:  # Limit to 3
                file_path = issue.get("file", "unknown")
                desc = issue.get("description", "No description")
                comment += f"- **{file_path}** - {desc}\n"
            comment += "\n"
    
    if suggestions:
        comment += "## 💡 Suggestions\n\n"
        for suggestion in suggestions:
            comment += f"- {suggestion}\n"
        comment += "\n"
    
    comment += "---\n*This review was generated by AI. Please address high-severity issues before merging.*"
    
    return comment


def main():
    """Main execution function"""
    # Get environment variables
    github_token = os.getenv('GITHUB_TOKEN')
    openai_api_key = os.getenv('OPENAI_API_KEY')
    github_repo = os.getenv('GITHUB_REPOSITORY')
    pr_number = os.getenv('PR_NUMBER')
    model = os.getenv('OPENAI_MODEL', 'gpt-4o')
    
    # Validate required environment variables
    missing_vars = []
    if not github_token:
        missing_vars.append('GITHUB_TOKEN')
    if not openai_api_key:
        missing_vars.append('OPENAI_API_KEY')
    if not github_repo:
        missing_vars.append('GITHUB_REPOSITORY')
    if not pr_number:
        missing_vars.append('PR_NUMBER')
    
    if missing_vars:
        print(f"❌ Missing required environment variables: {', '.join(missing_vars)}")
        sys.exit(1)
    
    # Initialize GitHub API
    github_api = GitHubAPI(github_token, github_repo)
    
    try:
        # Get PR diff
        print(f"📥 Fetching PR #{pr_number} diff...")
        diff = github_api.get_pr_diff(int(pr_number))
        
        if not diff:
            print("⚠️  No diff found for this PR")
            github_api.post_comment(
                int(pr_number),
                "⚠️ **AI Review Skipped**\n\nNo diff found for this PR."
            )
            sys.exit(0)
        
        print(f"📊 Diff size: {len(diff)} characters")
        
        # Truncate diff if too large (OpenAI has token limits)
        max_diff_size = 50000  # ~50k chars
        if len(diff) > max_diff_size:
            print(f"⚠️  Diff is large ({len(diff)} chars), truncating to {max_diff_size} chars")
            diff = diff[:max_diff_size] + "\n\n... (diff truncated due to size)"
        
        # Run AI review
        print("🤖 Running AI review...")
        review_result = review_pr_with_ai(diff, openai_api_key, model)
        
        # Format and post comment
        comment = format_review_comment(review_result, int(pr_number))
        github_api.post_comment(int(pr_number), comment)
        
        # Print summary
        decision = review_result.get("decision", "UNKNOWN")
        severity = review_result.get("severity", "NONE")
        issues_count = len(review_result.get("issues", []))
        
        print(f"✅ AI Review Complete")
        print(f"   Decision: {decision}")
        print(f"   Severity: {severity}")
        print(f"   Issues Found: {issues_count}")
        
        # Exit with error if FAIL
        if decision == "FAIL" or severity == "HIGH":
            print("❌ PR FAILED: High-severity issues detected by AI")
            sys.exit(1)
        else:
            print("✅ PR PASSED: AI review found no critical issues")
            sys.exit(0)
            
    except Exception as e:
        error_msg = f"❌ Error during AI review: {str(e)}"
        print(error_msg)
        try:
            github_api.post_comment(
                int(pr_number),
                f"❌ **AI Review Error**\n\n{error_msg}"
            )
        except:
            pass
        sys.exit(1)


if __name__ == '__main__':
    main()

